name: tripapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  dots_indicator: ^2.0.0
  firebase_auth: ^3.0.1
  eva_icons_flutter: ^3.0.0
  url_launcher: ^6.0.9
  flutter_linkify: ^5.0.2
  image_picker: ^0.8.3+2
  cloud_firestore: ^2.5.0
  firebase_storage: ^10.0.2
  status_change: ^2.0.0
  intl: ^0.17.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/airplane.png
    - assets/images/hikoki_animated.gif
    - assets/images/2525.png
    - assets/images/hokkaido.png
    - assets/images/aomori.png
    - assets/images/iwate.png
    - assets/images/akita.png
    - assets/images/miyagi.png
    - assets/images/yamagata.png
    - assets/images/hokkaido.jpeg
    - assets/images/aomori.jpeg
    # - assets/images/iwate.jpeg
    # - assets/images/miyagi.jpeg
    # - assets/images/akita.jpeg
    # - assets/images/yamagata.jpeg
    # - assets/images/hukushima.jpeg
    # - assets/images/ibaraki.jpeg
    # - assets/images/tochigi.jpeg
    # - assets/images/gunma.jpeg
    # - assets/images/saitama.jpeg
    # - assets/images/chiba.jpeg
    # - assets/images/tokyo.jpeg
    # - assets/images/kanagawa.jpeg
    # - assets/images/niigata.jpeg
    # - assets/images/toyama.jpeg
    # - assets/images/ishikawa.jpeg
    # - assets/images/fukui.jpeg
    # - assets/images/yamanashi.jpeg
    # - assets/images/nagano.jpeg
    # - assets/images/gihu.jpeg
    # - assets/images/shizuoka.jpeg
    # - assets/images/aichi.jpeg
    # - assets/images/mie.jpeg
    # - assets/images/shiga.jpeg
    # - assets/images/kyoto.jpeg
    # - assets/images/osaka.jpeg
    # - assets/images/hyogo.jpeg
    # - assets/images/nara.jpeg
    # - assets/images/wakayama.jpeg
    # - assets/images/tottori.jpeg
    # - assets/images/shimane.jpeg
    # - assets/images/okayama.jpeg
    # - assets/images/hiroshima.jpeg
    # - assets/images/yamaguchi.jpeg
    # - assets/images/tokushima.jpeg
    # - assets/images/kagawa.jpeg
    # - assets/images/ehime.jpeg
    # - assets/images/kouchi.jpeg
    # - assets/images/fukuoka.jpeg
    # - assets/images/saga.jpeg
    # - assets/images/nagasaki.jpeg
    # - assets/images/kumamoto.jpeg
    # - assets/images/oita.jpeg
    # - assets/images/miyazaki.jpeg
    # - assets/images/kagoshima.jpeg
    # - assets/images/okinawa.jpeg